import os
from fpdf import FPDF
from datetime import datetime

class DynamicSARPDF(FPDF):
    def __init__(self, jurisdiction):
        super().__init__()
        self.jurisdiction = jurisdiction

    def header(self):
        # Dynamically change the Header based on Jurisdiction
        self.set_font("Arial", "B", 14)
        
        if self.jurisdiction == "USA (FinCEN)":
            self.cell(0, 10, "FinCEN Suspicious Activity Report (SAR)", ln=True, align="C")
            self.set_font("Arial", "I", 10)
            self.cell(0, 5, "OMB No. 1506-0065 | Form 111 | PART V: Narrative Attachment", ln=True, align="C")
        
        elif self.jurisdiction == "UK (NCA)":
            self.cell(0, 10, "National Crime Agency (NCA) / FCA", ln=True, align="C")
            self.set_font("Arial", "I", 10)
            self.cell(0, 5, "Suspicious Activity Report (SAR) | Market Abuse Regulation", ln=True, align="C")
            
        else: # Default to India
            self.cell(0, 10, "Financial Intelligence Unit - India (FIU-IND)", ln=True, align="C")
            self.set_font("Arial", "I", 10)
            self.cell(0, 5, "Suspicious Transaction Report (STR) | PART 7: Grounds of Suspicion", ln=True, align="C")
            
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        # Add a dynamic security footer
        footer_text = f"CONFIDENTIAL | Generated by Aletheia AI | Jurisdiction: {self.jurisdiction} | Page {self.page_no()}"
        self.cell(0, 10, footer_text, 0, 0, "C")

def generate_sba_pdf(narrative, df, jurisdiction="India (FIU-IND)"):
    # Sanitize LLM artifacts (fix the bullet point error from earlier!)
    safe_narrative = (narrative
        .replace('₹', 'INR ')
        .replace('**', '')       
        .replace('•', '-')       
        .replace('“', '"')       
        .replace('”', '"')
        .replace('‘', "'")
        .replace('’', "'")
        .replace('—', '-')       
        .replace('–', '-')       
    )
    
    # Initialize the dynamic PDF
    pdf = DynamicSARPDF(jurisdiction)
    pdf.add_page()
    
    # Add Report Metadata
    pdf.set_font("Arial", "B", 11)
    pdf.cell(50, 8, "Date Generated:", border=1)
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 8, f" {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", border=1, ln=True)
    
    # Get Suspect Account No (assuming all rows belong to the filtered suspect)
    suspect_acct = df['account_no'].iloc[0] if not df.empty else "UNKNOWN"
    
    pdf.set_font("Arial", "B", 11)
    pdf.cell(50, 8, "Target Entity / Account:", border=1)
    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 8, f" {suspect_acct}", border=1, ln=True)
    
    pdf.ln(10)
    
    # Add the AI Narrative
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "OFFICIAL NARRATIVE / GROUNDS FOR SUSPICION", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    
    pdf.set_font("Arial", "", 11)
    # Multi_cell handles text wrapping automatically
    pdf.multi_cell(0, 6, safe_narrative.encode('latin-1', 'replace').decode('latin-1'))
    
    # Add the Evidence Ledger (Audit Trail)
    pdf.ln(10)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "APPENDIX: REFERENCED TRANSACTION LEDGER", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    
    pdf.set_font("Courier", "", 8)
    # Convert DataFrame to a clean string table for the PDF
    audit_data = df[['txn_date', 'txn_type', 'amount', 'counterparty', 'txn_id']].to_string(index=False)
    pdf.multi_cell(0, 5, audit_data)
    
    # Save the file
    filename = "Aletheia_Official_SAR.pdf"
    pdf.output(filename)
    return filename